name: yourls-custom
description: |
  YOURLS (Your Own URL Shortener) rodando a partir do seu fork.
  Crie e gerencie URLs curtas com este template que já puxa a última
  versão do seu repositório no GitHub e configura automaticamente
  o banco de dados MySQL interno.

instructions: Acesse /admin e use as credenciais definidas no deploy.

changeLog:
  - date: 2025-09-07
    description: Template personalizado Lagoo (baseado em v1.10.2)

links:
  - label: Documentação YOURLS
    url: https://yourls.org/#Guide
  - label: Repositório Fork
    url: https://github.com/tiagomarcal55/YOURLS

contributors:
  - name: Tiago Marçal
    url: https://github.com/tiagomarcal55

schema:
  type: object
  required:
    - appServiceName
    - databaseServiceName
    - db_pass
    - user
    - pass
  properties:
    appServiceName:
      type: string
      title: Nome do serviço de app
      default: yourls
    databaseServiceName:
      type: string
      title: Nome do serviço de banco
      default: yourls-db
    db_pass:
      type: string
      title: Senha MySQL root
      secret: true
    user:
      type: string
      title: Usuário admin YOURLS
      default: lagoo
    pass:
      type: string
      title: Senha admin YOURLS
      secret: true

benefits:
  - title: Deploy automático
    description: Puxa sempre o seu fork com a última versão.
  - title: Credenciais seguras
    description: Senhas armazenadas como secrets no Easypanel.
  - title: Configuração zero
    description: Banco interno configurado sem você tocar em nada.

features:
  - title: Atualização contínua
    description: Seu código no GitHub sempre aplicado no deploy.
  - title: Flexibilidade
    description: Customize variáveis e domínios sem alterar o repo.
  - title: Segurança
    description: Senhas de banco e admin nunca ficam no código.

tags:
  - URL Shortener
  - Self-Hosted
  - MySQL
